### ISSUE TITLE
Images replacement issue due to CDN servers

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#216]
the issue created by using CDN  servers...whenever we replace any already uploaded image...it will not show on the website although it is properly replaced in backend

as discussed it is due to CDN servers and you need to change some settings in that....this is just a reminder for that :)

**Comment by arshadansari27** [comment]
I have fixed it.. but it needs cdn level testing.. 

The way to test is to go to each activity for which you have replaced the image and then just save it, in order to modify the date.. it should show the new image on site, once the save is complete... if any doubt, call me...

**Comment by YunusDange** [comment]
Cool....It's working

On Fri, Jun 5, 2015 at 1:11 AM, Mohammed Arshad Ansari <
notifications@github.com> wrote:

> Closed #216 <https://github.com/arshadansari27/fitranginew/issues/216>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arshadansari27/fitranginew/issues/216#event-322865443>
> .
>



-- 

-------------------------
warm regards,
*Yunus Dange*

cell: 98333 57288

email: yunusdange@gmail.com


FACEBOOK <https://www.facebook.com/Yuni002>
<https://www.facebook.com/Yuni002> |  TWITTER
<https://twitter.com/YunusDange>  |  LINKEDIN
<http://www.linkedin.com/in/yunusdange>
<http://www.youtube.com/user/FitRangi>


*"My India may not be great. but it will be soon."*

**Comment by YunusDange** [comment]
Is this issue solved permanently??...coz i find it again

i have uploaded a Gear dealer profile...and accidentally uploaded wrong size image which is not looking proper....so i replaced the image with proper Image but website is still showing old inappropriate image 

i have even tried and uploaded the new image with different name...but not working

check this 
http://www.fitrangi.com/profile/outdoortravelgear-com

**Comment by arshadansari27** [comment]
It should be fixed now.. I had make some changes earlier to fix it, but there were new changes that went to solve another problem which kind of broke this one. 
So I made a third fix just now.. Can u try?

**Comment by YunusDange** [comment]
This problem is not fixed...still see the same image
check again
http://www.fitrangi.com/profile/outdoortravelgear-com

i have even tried with uploading another images but it still show the same old image

**Comment by arshadansari27** [comment]
Like a said, CDN Image handling needs a proper solution that I have to think of. Right now there is only work around, which means more work for you. Whenever you update any image from admin panel, at the bottom of form, you will see "Page Cover Image" field with a path to media file. This field should be made empty after you update the image. This will ensure this path will load will new image once the original page on site is viewed by any one. You can verify that in the test run and it will load new image.
