### ISSUE TITLE
Forum Content Linking

### ISSUE THREAD

**Issue by YunusDange** [arshadansari27/fitranginew#25]
Whenever we ask any question OR answer any question , the website & other URL doesn't have link (means it can't be clicked). Like if i use "Visit: www.atconclave.com" then it doesn't appear as a link, instead it appears as a text only. SEE IF WE CAN SOLVE THIS PROBLEM ASAP. (see this commect only the website link is clickable :) )

**Comment by YunusDange** [comment]
Still Pending

**Comment by arshadansari27** [comment]
This has been fixed and links are visible

**Comment by YunusDange** [comment]
Not yet fixed... check this discussion 
http://fitrangi.com/model/Forum/5496c8dda5bfb65946577e70

The link in answer is not visible
